# Generated by Django 5.2.12 on 2026-03-18 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        (
            "django_tasks_database",
            "0019_rename_django_task_new_ordering_idx_tasks_db_new_ordering_idx_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="TaskLease",
            fields=[
                (
                    "task_result",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="lease",
                        serialize=False,
                        to="django_tasks_database.dbtaskresult",
                    ),
                ),
                ("expires_at", models.DateTimeField(db_index=True)),
            ],
            options={
                "verbose_name": "Task Lease",
                "verbose_name_plural": "Task Leases",
            },
        ),
    ]
